### ISSUE TITLE
The Singleton meta class unexpectedly raises a TypeError when we thought __instance__ existed

### ISSUE THREAD

**Issue by zancas** [contains-io/typet#16] opened 2018-01-07 21:32 UTC
In [4]: _RcliConfig.__call__()

TypeError                                 Traceback (most recent call last)
<ipython-input-4-baaa6c91805b> in <module>()
----> 1 _RcliConfig.__call__()

~/rcli/venv/lib/python3.6/site-packages/typet/meta.py in call(cls, args, **kwargs)
     78         else:
     79             try:
---> 80                 cls.__instance__.__singleton__(args, **kwargs)  # type: ignore
     81             except AttributeError:
     82                 pass

TypeError: 'NoneType' object is not callable

The code in question is here:

https://github.com/contains-io/typet/blob/master/typet/meta.py#L64

**Comment by dangle** [comment] 2018-01-13 23:43
Is this fixed with the catch for `TypeError`?

**Comment by zancas** [comment] 2018-01-16 20:56
I still don't understand where the `TypeError` in question is being raised.

**Comment by dangle** [comment] 2018-01-16 23:52
The issue is that `__instance__` defaults to `None`. The `if-statement` checks for falsey then tries to run it, but then it tries to call `__singleton__` on `__instance__` which is `None`. Maybe a better idea would be to change that else to `elif cls.__instance__ is not None:` instead of catching `TypeError`.

**Comment by dangle** [comment] 2018-01-17 01:12
I think this is fine with the `TypeError` check. Closing this for now.

**Closed as completed by dangle** 2018-01-17 01:12 UTC
